export const FETCH_IMAGE_LINK_REQUEST = "FETCH_IMAGE_LINK_REQUEST";
export const FETCH_IMAGE_LINK_SUCCESS = "FETCH_IMAGE_LINK_SUCCESS";
export const FETCH_IMAGE_LINK_FAILURE = "FETCH_IMAGE_LINK_FAILURE";